-- invis.lua
-- ==========================
-- Documentation header below generated by LLM, and then edited
--
-- Shortcode: {{< invis start >}} / {{< invis end >}}
--
-- Purpose:
--   Hide content visually while keeping it accessible to screen readers
--   or optionally invisible in PDF/LaTeX output.
--
-- HTML:
--   - Default inline: <span class="invisible-text">
--   - Optional block mode: <div class="invisible-text">
--   - Accessibility:
--       * Screen readers get explicit start/end notes using sr-only spans
--       * Container has aria-label describing hidden content
--
-- PDF/LaTeX:
--   - \begingroup\color{white} ... \endgroup wraps hidden content
--   - Warnings for missing parameters are shown in red (\textcolor)
--   - IMPORTANT: this shortcode uses the xcolor package
--     If your document does not already load it, you can add in your YAML:
--       header-includes: |
--         \usepackage{xcolor}
--     NOTE: Loading xcolor twice with different options can cause errors.

--
-- Usage:
--   Inline (default):
--     {{< invis start >}}hidden text{{< invis end >}}
--
--   Block:
--     {{< invis start block >}}
--     Hidden multi-line content
--     {{< invis end block >}}
--
-- Notes:
--   - Default mode is inline; use "block" as second argument for multi-line content
--   - Screen-reader notes are prepended/appended via sr-only spans
--   - aria-label gives a semantic description of the hidden content
-- ==========================

-- Setting up dependencies - loading the local css for html 
-- and forcing latex header to load xcolor package

local utils = pandoc.utils

-- Screen-reader notes for HTML
local sr_start = '<span class="sr-only">Note: the following content is visually hidden.</span>'
local sr_end   = '<span class="sr-only">End of visually hidden content.</span>'

local aria_note = 'Contains some intentionally invisible text'

-- Add CSS dependency for HTML
if quarto.doc.isFormat("html") then
  quarto.doc.add_html_dependency({
    name = "invis-css",
    version = "1.0",
    stylesheets = {'invis.css'}
  })
end

return {
  ['invis'] = function(args, kwargs, meta, raw_args, context)
    -- Check for a meta variable to disable invisibility
    local disable = meta and meta["invis"]
    if disable == false or (type(disable) == "string" and utils.stringify(disable):lower() == "false") then
      return pandoc.Null() -- Do nothing, ignore shortcodes entirely
    end

    -- Read first argument (start / end)
    -- param should be 'start' or 'end' with optional 'block' afterwards
    local param = args and args[1] and utils.stringify(args[1]):lower() or nil
    if not param then
      if quarto.doc.isFormat("pdf") or quarto.doc.isFormat("latex") then
        return pandoc.RawInline("tex", "\\textcolor{red}{[invis: missing parameter, likely missing 'start' or 'end']} ")
      else
        return pandoc.Str("[invis: missing parameter, likely missing 'start' or 'end' here]")
      end
    end

    -- Optional second argument: "block" to force <div> wrapping not <span>
    local mode = args and args[2] and utils.stringify(args[2]):lower() or nil
    local is_block = mode == "block"

    -- Detect PDF/LaTeX
    local is_pdf = quarto.doc.isFormat("pdf") or quarto.doc.isFormat("latex")
    local is_html = quarto.doc.isFormat("html")

    -- HTML output helper, includes adding screen-reader text and checking block
    local function html_output(first, second)
      local content = (first or "") .. second
      return is_block and pandoc.RawBlock("html", content) or pandoc.RawInline("html", content)
    end

    -- HTML
    if is_html then
      if param == "start" then
        local open_tag = is_block 
          and '<div class="invisible-text" aria-label="' .. aria_note .. '">' 
          or '<span class="invisible-text" aria-label="' .. aria_note .. '">' 
        return html_output(open_tag, sr_start)
      elseif param == "end" then
        local close_tag = is_block and '</div>' or '</span>'
        return html_output(sr_end, close_tag)
      else
        return pandoc.Str("[invis: invalid param]")
      end

    -- PDF/LaTeX
    elseif is_pdf then
      if param == "start" then
        return pandoc.RawInline("tex", "\\begingroup\\color{white}")
      elseif param == "end" then
        return pandoc.RawInline("tex", "\\endgroup")
      else
        return pandoc.Str("[invis: invalid param]")
      end

    else
      return pandoc.Str("[invis: unsupported format]")
    end
  end
}
